### ISSUE TITLE
Outdoor datasets fine-tuning

### ISSUE THREAD

**Issue by Edric-star** [DepthAnything/Depth-Anything-V2#109]
Dear author, 
            Hi, may I ask that what did you do while fine-tuning the vkitti datasets? Are there any special strategies to deal with the sky? @LiheYoung

**Comment by Edric-star** [comment]
> Hi, we discard the sky region in loss computation. Actually, we discard any pixel whose depth is larger than 80 meters.

OK, got it, thanks

**Comment by xiaodongww** [comment]
@LiheYoung Hi, will there be a problem when you inference a image if you simply discard farway pixels? 

Specifically, the predicted depth for sky regions could be quite noisy since the model has never encountered them during training. This might result in small depth values for the sky, causing issues when generating a point cloud from the predicted depth. You'd get noisy 'sky points'.

This problem isn't limited to sky regions; it affects all distant areas, like faraway buildings too. This makes it difficult to filter out noisy points using semantic segmentation. Do I understand this correctly?

Thanks for your help!
