### ISSUE TITLE
How can I modify the model code to reduce the number of transformer layers? Currently, there are 12 layers？ and I want to decrease it to 4 layers.

### ISSUE THREAD

**Issue by laobadao** [DepthAnything/Depth-Anything-V2#187]
1. 基于 vits 模型， vit_small 中 depth = 12, 是修改这个地方吗？改成 4 可以吗？
![image](https://github.com/user-attachments/assets/7eb98f8f-9b2c-4a5f-b4bb-66f59b02ee4a)

![image](https://github.com/user-attachments/assets/5ef74f3f-02c8-4bb7-ae50-28dffc47bcae)
![image](https://github.com/user-attachments/assets/b5860f8e-716c-4f9e-8361-473283357db3)
请问下，DPTHead foward 输出这个地方怎么修改？

你好，现在的需求是，模型 small  还是有些大，想适配端侧芯片，想缩减层数。

**Comment by heyoeyo** [comment]
Aside from the changes you've already listed, the [intermediate layer indexing](https://github.com/DepthAnything/Depth-Anything-V2/blob/31dc97708961675ce6b3a8d8ffa729170a4aa273/depth_anything_v2/dpt.py#L165) will also need to be modified to only use those 4 layers:
```python
# Modified indexing for vit-s with only 4 layers
self.intermediate_layer_idx = {'vits': [0,1,2,3]}
```

**Comment by R0nSam** [comment]
Hi can you tell me what you did to modify the layers to 4?
is there any speed improvement?

**Comment by heyoeyo** [comment]
> Hi can you tell me what you did to modify the layers to 4?

You'd have to set [depth to 4](https://github.com/DepthAnything/Depth-Anything-V2/blob/e5a2732d3ea2cddc081d7bfd708fc0bf09f812f1/depth_anything_v2/dinov2.py#L343) for whatever model size you want to use, and then change the `intermediate_layer_idx` to `[0,1,2,3]` as described above. If you try to load the original weights, you also have to set `strict=false` when calling `load_state_dict`, so that it doesn't fail due to the weights mismatching the modified sizing.

> is there any speed improvement?

The small ViT model has 12 layers originally, so that part of the model should run 3x faster if it's reduced to 4 layers. It won't effect the speed of the rest of the model components though.
