### ISSUE TITLE
About demo

### ISSUE THREAD

**Issue by zzzcyyyw** [DepthAnything/Depth-Anything-V2#2]
Hi, may I ask which one of the following models you are using for the demo you released?
1. Depth-Anything-V2-Small
2. Depth-Anything-V2-Base
3. Depth-Anything-V2-Large
4. Depth-Anything-V2-Giant

**Comment by LiheYoung** [comment]
We use Depth-Anything-V2-Large in our online demo, since we are still going through company review process to release the best Depth-Anything-V2-Giant model. See [here](https://huggingface.co/spaces/depth-anything/Depth-Anything-V2/blob/ac64c096fd1a0311dc837620b1664340e0659c0b/app.py#L42-L44) for details.

**Comment by zzzcyyyw** [comment]
Okay, thank you very much for your reply!
