### ISSUE TITLE
metric_depth图像格式请教

### ISSUE THREAD

**Issue by ai-shen** [DepthAnything/Depth-Anything-V2#227]
metric_depth/dataset/splits/hypersim，这里的数据集使用到了图像和深度图，图像使用的是tonemap的，请问可以使用color图像吗？不知道有什么样的区别？
/mnt/bn/liheyang/DepthDatasets/HyperSim/all/ai_001_001/images/scene_cam_00_final_preview/frame.0000.**tonemap**.jpg /mnt/bn/liheyang/DepthDatasets/HyperSim/all/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.depth_meters.hdf5

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Hypersim dataset class to allow using color images instead of tonemap images. Added a new parameter 'use_color_images' to the constructor and updated the image loading process accordingly.

You can review changes in this commit: https://github.com/kkpo4553/DepthAnything-Depth-Anything-V2-227/commit/afac5fada1a09e930019761e2dd0bf420498ca50.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by LiheYoung** [comment]
可以参考这里https://github.com/apple/ml-hypersim/tree/main#lossless-high-dynamic-range-images, tone mapping后的图像在色调上和原始的color图像存在一些差别。

**Comment by ai-shen** [comment]
> 可以参考这里https://github.com/apple/ml-hypersim/tree/main#lossless-high-dynamic-range-images, tone mapping后的图像在色调上和原始的color图像存在一些差别。

好的，非常感谢！
